name: My cool workflow

on: 
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
    myfirstjob:
              name: First job
              runs-on: ubuntu-latest
              steps:
              - name: Step One
                uses: actions/checkout@v3
              - name: Step Two
                run: | 
                  touch newfile.yaml
                  echo "Please Alex is Fridat let me escape" >> newfile.yaml
                  cat newfile.yaml
                  pwd
    mysecondjob:
              needs: [myfirstjob]
              name: SecondJob job
              runs-on: macos-latest
              steps:
              - name: Step One
                run: date
    mythirdjob:
              name: Third job
              runs-on: windows-latest
              steps:
              - name: Step One
                run: date
    
